// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: causal.proto

package v1alpha1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CausalDiscoveryClient is the client API for CausalDiscovery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CausalDiscoveryClient interface {
	Discover(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*CausalGraph, error)
}

type causalDiscoveryClient struct {
	cc grpc.ClientConnInterface
}

func NewCausalDiscoveryClient(cc grpc.ClientConnInterface) CausalDiscoveryClient {
	return &causalDiscoveryClient{cc}
}

func (c *causalDiscoveryClient) Discover(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*CausalGraph, error) {
	out := new(CausalGraph)
	err := c.cc.Invoke(ctx, "/causal.v1alpha1.CausalDiscovery/Discover", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CausalDiscoveryServer is the server API for CausalDiscovery service.
// All implementations must embed UnimplementedCausalDiscoveryServer
// for forward compatibility
type CausalDiscoveryServer interface {
	Discover(context.Context, *DiscoverRequest) (*CausalGraph, error)
	mustEmbedUnimplementedCausalDiscoveryServer()
}

// UnimplementedCausalDiscoveryServer must be embedded to have forward compatible implementations.
type UnimplementedCausalDiscoveryServer struct {
}

func (UnimplementedCausalDiscoveryServer) Discover(context.Context, *DiscoverRequest) (*CausalGraph, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Discover not implemented")
}
func (UnimplementedCausalDiscoveryServer) mustEmbedUnimplementedCausalDiscoveryServer() {}

// UnsafeCausalDiscoveryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CausalDiscoveryServer will
// result in compilation errors.
type UnsafeCausalDiscoveryServer interface {
	mustEmbedUnimplementedCausalDiscoveryServer()
}

func RegisterCausalDiscoveryServer(s grpc.ServiceRegistrar, srv CausalDiscoveryServer) {
	s.RegisterService(&CausalDiscovery_ServiceDesc, srv)
}

func _CausalDiscovery_Discover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CausalDiscoveryServer).Discover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/causal.v1alpha1.CausalDiscovery/Discover",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CausalDiscoveryServer).Discover(ctx, req.(*DiscoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CausalDiscovery_ServiceDesc is the grpc.ServiceDesc for CausalDiscovery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CausalDiscovery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "causal.v1alpha1.CausalDiscovery",
	HandlerType: (*CausalDiscoveryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Discover",
			Handler:    _CausalDiscovery_Discover_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "causal.proto",
}

// CausalSimulationClient is the client API for CausalSimulation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CausalSimulationClient interface {
	Simulate(ctx context.Context, in *SimulateRequest, opts ...grpc.CallOption) (*SimulateResponse, error)
}

type causalSimulationClient struct {
	cc grpc.ClientConnInterface
}

func NewCausalSimulationClient(cc grpc.ClientConnInterface) CausalSimulationClient {
	return &causalSimulationClient{cc}
}

func (c *causalSimulationClient) Simulate(ctx context.Context, in *SimulateRequest, opts ...grpc.CallOption) (*SimulateResponse, error) {
	out := new(SimulateResponse)
	err := c.cc.Invoke(ctx, "/causal.v1alpha1.CausalSimulation/Simulate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CausalSimulationServer is the server API for CausalSimulation service.
// All implementations must embed UnimplementedCausalSimulationServer
// for forward compatibility
type CausalSimulationServer interface {
	Simulate(context.Context, *SimulateRequest) (*SimulateResponse, error)
	mustEmbedUnimplementedCausalSimulationServer()
}

// UnimplementedCausalSimulationServer must be embedded to have forward compatible implementations.
type UnimplementedCausalSimulationServer struct {
}

func (UnimplementedCausalSimulationServer) Simulate(context.Context, *SimulateRequest) (*SimulateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Simulate not implemented")
}
func (UnimplementedCausalSimulationServer) mustEmbedUnimplementedCausalSimulationServer() {}

// UnsafeCausalSimulationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CausalSimulationServer will
// result in compilation errors.
type UnsafeCausalSimulationServer interface {
	mustEmbedUnimplementedCausalSimulationServer()
}

func RegisterCausalSimulationServer(s grpc.ServiceRegistrar, srv CausalSimulationServer) {
	s.RegisterService(&CausalSimulation_ServiceDesc, srv)
}

func _CausalSimulation_Simulate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimulateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CausalSimulationServer).Simulate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/causal.v1alpha1.CausalSimulation/Simulate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CausalSimulationServer).Simulate(ctx, req.(*SimulateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CausalSimulation_ServiceDesc is the grpc.ServiceDesc for CausalSimulation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CausalSimulation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "causal.v1alpha1.CausalSimulation",
	HandlerType: (*CausalSimulationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Simulate",
			Handler:    _CausalSimulation_Simulate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "causal.proto",
}
