# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import causal_pb2 as causal__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in causal_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CausalDiscoveryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Discover = channel.unary_unary(
                '/causal.v1alpha1.CausalDiscovery/Discover',
                request_serializer=causal__pb2.DiscoverRequest.SerializeToString,
                response_deserializer=causal__pb2.CausalGraph.FromString,
                _registered_method=True)


class CausalDiscoveryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Discover(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CausalDiscoveryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Discover': grpc.unary_unary_rpc_method_handler(
                    servicer.Discover,
                    request_deserializer=causal__pb2.DiscoverRequest.FromString,
                    response_serializer=causal__pb2.CausalGraph.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'causal.v1alpha1.CausalDiscovery', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('causal.v1alpha1.CausalDiscovery', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CausalDiscovery(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Discover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/causal.v1alpha1.CausalDiscovery/Discover',
            causal__pb2.DiscoverRequest.SerializeToString,
            causal__pb2.CausalGraph.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CausalSimulationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Simulate = channel.unary_unary(
                '/causal.v1alpha1.CausalSimulation/Simulate',
                request_serializer=causal__pb2.SimulateRequest.SerializeToString,
                response_deserializer=causal__pb2.SimulateResponse.FromString,
                _registered_method=True)


class CausalSimulationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Simulate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CausalSimulationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Simulate': grpc.unary_unary_rpc_method_handler(
                    servicer.Simulate,
                    request_deserializer=causal__pb2.SimulateRequest.FromString,
                    response_serializer=causal__pb2.SimulateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'causal.v1alpha1.CausalSimulation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('causal.v1alpha1.CausalSimulation', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CausalSimulation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Simulate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/causal.v1alpha1.CausalSimulation/Simulate',
            causal__pb2.SimulateRequest.SerializeToString,
            causal__pb2.SimulateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
